update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,6 @@
-name: CI for Main Branch
+ name: CI for Main Branch
 
-on:
+ on:
   push:
     branches:
       - main
@@ -8,42 +8,42 @@ on:
     branches:
       - main
 
-jobs:
+ jobs:
   build-and-test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Build Docker image
-        run: docker build -t myapp:${{ github.sha }} .
+#       - name: Build Docker image
+#         run: docker build -t myapp:${{ github.sha }} .
 
-      - name: Install trivy
-        run: |
-          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
-          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
-          sudo apt-get update
-          sudo apt-get install trivy
+#       - name: Install trivy
+#         run: |
+#           wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
+#           echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
+#           sudo apt-get update
+#           sudo apt-get install trivy
 
-      - name: Run Trivy vulnerability scan
-        run: trivy image myapp:${{ github.sha }} --format json > trivy-report.json
+#       - name: Run Trivy vulnerability scan
+#         run: trivy image myapp:${{ github.sha }} --format json > trivy-report.json
 
-      - name: Download process vulnerability report script
-        run: curl -o process_vulnerability_report.py https://raw.githubusercontent.com/mikigbo/devops-tools/main/process_vulnerability_report.py
+#       - name: Download process vulnerability report script
+#         run: curl -o process_vulnerability_report.py https://raw.githubusercontent.com/mikigbo/devops-tools/main/process_vulnerability_report.py
 
-      - name: Process vulnerability report
-        run: python process_vulnerability_report.py trivy-report.json
+#       - name: Process vulnerability report
+#         run: python process_vulnerability_report.py trivy-report.json
 
-      - name: Determine success or failure
-        run: |
-          if [ $? -eq 0 ]; then
-            echo "Vulnerability check passed. Proceeding with deployment."
-          else
-            echo "Vulnerability check failed. Halting deployment."
-            exit 1
-          fi
+#       - name: Determine success or failure
+#         run: |
+#           if [ $? -eq 0 ]; then
+#             echo "Vulnerability check passed. Proceeding with deployment."
+#           else
+#             echo "Vulnerability check failed. Halting deployment."
+#             exit 1
+#           fi
 
-      - name: Test Docker image
-        run:  docker run -e JWT_SECRET=${{ secrets.JWT_SECRET }} myapp:${{ github.sha }} npm test
-        continue-on-error: false  # Ensure the workflow fails if tests fail
+#       - name: Test Docker image
+#         run:  docker run -e JWT_SECRET=${{ secrets.JWT_SECRET }} myapp:${{ github.sha }} npm test
+#         continue-on-error: false  # Ensure the workflow fails if tests fail
 
